#!/bin/sh
#
# WARNING: This script is for LRM regressions tests only
#

. /etc/ha.d/resource.d//hto-mapfuncs

case $# in
  1)	op=$1;;
  2)	export OCF_RESKEY_delay; OCF_RESKEY_delay=$1; op=$2;;
esac

OCF_TYPE=lrmregtest
OCF_RESOURCE_INSTANCE=heartbeat
export OCF_TYPE OCF_RESOURCE_INSTANCE

ra_execocf $op
